### ISSUE TITLE
Add topic tag `geospatial`

### ISSUE THREAD

**Issue by Beliavsky** [Francesco-Uboldi/projcoonv#1]
I suggest adding the topic tag `geospatial` in the About section, as explained at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics

**Comment by Francesco-Uboldi** [comment]
Thank you, I just did

**Comment by Francesco-Uboldi** [comment]
I added the suggested tag  `geospatial`, and also: `fortran` and `geographic-coordinates`
